language: node_js
node_js:
  - "10"

script:
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: gh-pages
  target-branch: gh-pages
  on:
    branch: master